const actionBookTypes = {
	LOAD_REQUEST: 'LOAD_REQUEST',
	LOAD_SUCCESS: 'LOAD_SUCCESS',
	LOAD_FAILURE: 'LOAD_FAILURE',
};

const actionStockTypes = {
	LOAD_STOCK: 'LOAD_STOCK',
	INSERT_FROM_STOCK: 'INSERT_FROM_STOCK',
	REMOVE_FROM_STOCK: 'REMOVE_FROM_STOCK',
	FAILURE_STOCK: 'FAILURE_STOCK',
};

export { actionBookTypes, actionStockTypes };
